# Set theme
remote_theme: daviddarnes/alembic@main

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji
- jekyll-remote-theme

# Site settings
url: 'https://juliambowden.github.io'
baseurl: '/fertiglab'
title: 'Fertig Lab'
description: 'The website for Fertig Lab'
permalink: pretty
logo: "/images/FertigLabLogo.png"
favicons: "/images/FertigLabFavicon.png"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: Biography
  url: /biography/
- title: Research Areas
  url: /research/
- title: Lab Members
  url: /lab-members/
- title: Publications
  url: /publications/
- title: Software
  url: /software/
- title: Teaching
  url: /teaching/
- title: Opportunities
  url: /opportunities/

  # Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: New York # Timezone for blog posts and alike

# Footer nav
navigation_footer:
- title: Site created by Julia Bowden
  url: "https://github.com/juliambowden"
- title: Back to top
  url: "#top"

# Collections
collections:
  posts:
    title: Posts
    output: true
    description: "My thoughts and ideas"
    feature_text: |
      Welcome to my blog
    feature_image: "/images/EnterTheMatrix.png"

# Collection settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages

fonts:
  preconnect_urls:
    - https://fonts.gstatic.com
  font_urls:
    - https://fonts.googleapis.com/css2?family=Merriweather:wght@400;700&display=swap
